language: node_js
node_js: 10
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
env:
    global:
        - GITHUB_REPO: bitshares/bitshares-ui
        - WALLET_REPO: bitshares/wallet.bitshares.org
        - STAGING_REPO: bitshares/bitshares-ui-staging
        - DEVELOP_REPO: bitshares/develop.bitshares.org
        - CXX=g++-4.8
        - secure:
              up459CkvN8cdhCHu4E2jAse5CM3JUJlVMbBu2x1HctFjanu4rv2JknIn5U4Rc6rX89GgLLJeUN05UsZEz+M+s5P7b8wlwkTKu1cdNFmcS1oDAJh3Gk22F3zGiv/HIQazjGCajMxX0kIsjNsHngAd/wJCvGrnLBU5vetu6zqCK/jR/YMGRl9bNTygH07eC4r5I7EKFRJLA8pM3GfBlG04aPS4feIrCiT+TAVENx3hLC2eKs451e3ktMYM5nh89E5HKjg2rfmwmIJRzuC/Rv5Dpk/3A77mOUe3iwZZWrmwUinlEfLBPn6zUD/XX83DI+7nINyUY13vDGZiMkwygvM6QZrReQZfZSVOaAfIZ7WoWIQd5SYFDj0fTGbdTxgwISr13LSHFQN+YsWkdbvnuKKXpaTwW+rRXU4pWXjaOQtNyr2nvp1AiW6TYzmq5ECbQ0IE2versZczasOLSk2E1h9vHw0SXrfqDR/X7WMIdKOuv1Umre30gcRZi5/0ZdcvfeY8jtdTwfsYoywtAQ3vfMelfDafIAtYPjFEhaeBZDDFGfMX5XAI0Rx34jQX7W1+76gR17l2V9kOwzKp/p5LNQh8kGzxyMY8Hl2xapwt/RG3tTnPXZeazFenYvybVCXPb46+Vqa/pxQyxB0HFu+izPTCiFfvd5rELyFkQT3kSNKFuio=
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - icnsutils
            - graphicsmagick
            - xz-utils
install:
    - npm ci
script:
    - "./build.sh"
after_success: "./deploy.sh"
deploy:
    - provider: releases
      tag_name: "$TRAVIS_TAG"
      name: "$TRAVIS_TAG"
      body:
          "Automated release from Travis CI with added files from AppVeyor build"
      api_key:
          secure:
              HV4BRj0Nn4+3AGC5U2LxFQ3qr6bbwcs2SR7BIEKXdHcIAshvL52Qn9R2pXFjeJhj/FqGMRc6o1E54q4+QpzzlnoZquZkJoSv4x4EW306KVXNxaBQmwjNLs6gO09/s8j3IlZ0pudANmH2WQvT264ldGCqq0mC1vCMpHfxetdGsskfqdboFgyaUSDtRBER9FH23cM22Ro3oPJmRxn/dzZSctiB05e1i8CD6VZm8HeGuWKXyKOuhzBFzEgaSkSQWa6u5YsvAKkQ4c6rAAxUWJOH9+8WoqUVN/Pem56mnA0HYtqAoX/cShLuZfsHRJUVdE5Wt9YfEOBRQy954QmZgPhQbp7OKcIBAQyAkMSR1AEKCYd2QjPBBM5ek44Pbz0AsDSd1qsSgKUJs4urpOTLbFi2KfDmaXiO+ciaIDvyh0QiUPykVdRtDKacdrHCWUUuJajc465KRE8LGheOGThj+s9vPmy9Eubn7Zzsdzy1q0Xjwjd57bz8G5aTbBWpJJ4sk096trJqGX1iQMKEpnEU/KwmRS9XX65s6gBjuO8/2ZhoE8HQCDBS0whiJi+eHggu6wch6SfTvATkQ9ivex6T/T/eYHGF+sbShkXrzmUs0sbsq1TrjgFyIA/x23y+0k59mZ8xfkRLHT3L1EjgW6MahwPCPESumomq3PDJrKPVpd7n/04=
      file_glob: true
      file:
          - build/binaries/BitShares*
          - build/release-checksums-*
      skip_cleanup: true
      draft: true
      on:
          repo: bitshares/bitshares-ui
          tags: true
    - provider: snap
      snap: bitshares2-light
      channel: candidate
      skip_cleanup: true
      on:
          tags: true
before_install:
    - openssl aes-256-cbc -K $encrypted_844f3e8bd137_key -iv $encrypted_844f3e8bd137_iv
      -in set_snap_token.sh.enc -out set_snap_token.sh -d
    - chmod +x set_snap_token.sh
    - source ./set_snap_token.sh
