language: node_js
node_js:
  - "10"

env:
  PATH=$PATH:$HOME/.local/bin
  S3_BUCKET_NAME="wallet.testnet.crypto-bridge.org"

cache:
  directories:
    - "node_modules"
    - "build"

install:
  - pip install --user awscli

jobs:
  include:
    # - stage: lint
    #   script:
    #     - npm install
    #     - npm run lint
    - stage: build
      script:
        - npm install
        - npm run build-testnet
    - stage: deploy
      script:
        - aws s3 cp ./build/dist/ s3://$S3_BUCKET_NAME/ --recursive
